[package]
name = "librint"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.155"

[profile.dev]
debug = true
opt-level = 0
debug-assertions = true
lto = "fat"

[profile.release]
lto = "fat"

[[bin]]
name = "h2_stv"
path = "grad/h2_stv.rs"

[[bin]]
name = "h2_stv_grad"
path = "grad/h2_stv_grad.rs"

[[bin]]
name = "h2_rep"
path = "grad/h2_rep.rs"

[[bin]]
name = "scf"
path = "grad/scf.rs"

[[bin]]
name = "reverse"
path = "ad/reverse.rs"

[[bin]]
name = "forward"
path = "ad/forward.rs"

[[bin]]
name = "backward"
path = "ad/backward.rs"